### PR TITLE
Implement Ticket to Deal Associations

### PR DESCRIPTION
**Pull request by avalanchis**
These changes implement Ticket to Deal associations.

### CODE REVIEW

**Comment by cdmdotnet** [comment]
Can you re-work/refactor this to be off the new trunk branch. This PR still has the setter properties we've done away with.

**Comment by avalanchis** [comment]
Will do.

**Comment by avalanchis** [comment]
Merged with latest trunk changes.  Tested and working in my environment.

**Comment by cdmdotnet** [comment]
TicketHubSpotModel.cs still has your previous changes include setter properties and ignore attributes.

**Comment by avalanchis** [comment]
Sorry I missed that the merge added that back in.  I've pushed an update to fix.

**Comment by cdmdotnet** [comment]
Merged and new package 1.5.2 released. Just needed a minor correction of an XML comment reference to a property within a method signature.

**Pull request merged**
