### PR TITLE
Implement basic contact list API operations

### PR DESCRIPTION
**Pull request by lakesol**
## Description
Implement basic contact list API operations

## Purpose
- [ ] Add support for get all contact lists
- [ ] Add support for get all static contact lists
- [ ] Add support to add a contact to a contact list
- [ ] Add support remove a contact from a contact list

### CODE REVIEW

**Comment by cdmdotnet** [comment]
Can you write a quick test (I know it's a console app, but it's what was there) to create a sample list, add a few members, query them back etc. Just something to verify it all works.

This might actually require just a small additional amount of work to create a list as I noticed that method isn't there in your code, but will make testing difficult if test lists cannot be created - https://legacydocs.hubspot.com/docs/methods/lists/create_list.

If I can run some tests and see it operates and does serialisation properly then there's no reason it won't get merged.

**Comment by lakesol** [comment]
> This might actually require just a small additional amount of work to create a list as I noticed that method isn't there in your code, but will make testing difficult if test lists cannot be created - https://legacydocs.hubspot.com/docs/methods/lists/create_list.

The issue I see is that the list creation could be quite an undertaking as if its going to be according to spec it should (in theory) include support for dynamic lists and that then includes the management of all the filters.

If you are OK with an implementation for creating a static list I can see that this would result in much less complexity.  I think that if the code is to tidy up after itself it will need to implement list deletion too.

**Comment by cdmdotnet** [comment]
Static list creation only is perfectly fine as that means gets can be tested, adding contacts (one of your methods) and yes... deletion can all be tested.

Just name the method appropriately so it's clear it's only static list creation. We can deal with method naming later on and breaking changes if the implementation is expanded to dynamic lists at a later date.

**Review by cdmdotnet — CHANGES_REQUESTED** [review]
See conversation train

**Pull request merged**
