### PR TITLE
Implement Tickets API

### PR DESCRIPTION
**Pull request by avalanchis**
Implemented support for HubSpot Ticket API.

### CODE REVIEW

**Comment by cdmdotnet** [comment]
Thanks for the contribution. If bugs arise or further requests for features to Tickets, do you have the capacity to support or is this more a case of "I need this and that's about as far as I can commit to"? Doesn't matter what the answer is, just let's me know if I should message you about them

**Comment by avalanchis** [comment]
> Thanks for the contribution. If bugs arise or further requests for features to Tickets, do you have the capacity to support or is this more a case of "I need this and that's about as far as I can commit to"? Doesn't matter what the answer is, just let's me know if I should message you about them

Sure, I have some capacity available if needed.

**Comment by cdmdotnet** [comment]
Can you provide a note on the PAT scopes necessary for your ticket tests please.

**Comment by avalanchis** [comment]
> Can you provide a note on the PAT scopes necessary for your ticket tests please.

The only scope that should be required is the "tickets" scope for all ticket related operations.

**Comment by cdmdotnet** [comment]
Merged to trunk and new packages deployed to Nuget. Thanks for the contribution.

**Pull request merged**
