### PR TITLE
Fix problems with TicketApi Update method

### PR DESCRIPTION
**Pull request by avalanchis**

### CODE REVIEW

**Comment by avalanchis** [comment]
This should resolve Issue #23

**Comment by cdmdotnet** [comment]
Ahhh. Not keen on having odd fields labelled XyzSetter.
What exactly was the issue experienced? Was it a serialisation issue while sending data? If so, wouldn't it be better to look at the serialiser logic for constructing JSON payloads?

**Comment by avalanchis** [comment]
The ticket's hs_ticket_id and hs_object_id properties are read only and HubSpot rejects PATCH requests that contain them.

**Comment by cdmdotnet** [comment]
Have a look at branch https://github.com/Chinchilla-Software-Com/HubSpot.NET/tree/bugs/patch-ticket-update-api

It's a cleaner way of dealing with the specifics of fields that mustn't be included and is in-line with the task API cludge that was done.
As mentioned, having separate setting properties isn't desirable.

Will it suffice your requirements?

**Comment by avalanchis** [comment]
Yes, that should work fine, but the integration test needs to be updated as follows:

Update TicketTests.cs, Line 100 to this:

`ticketApi.Delete(updatedTicket.Id.Value);`

That test succeeds on my environment.

**Comment by cdmdotnet** [comment]
New packages released to nuget.

**Pull request closed without merging**
